### PR TITLE
Panelapp gene query script added

### PR DESCRIPTION
**Pull request by g-pyxl**
Simple script to generate CSV containing all current gene/panel relations using PanelApp API.
Updated README.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
Suggestion to add a settings.json file - e.g. https://github.com/moka-guys/oncodeep_upload/blob/main/settings.json
This means the same formatting will be applied in vscode as in other existing team projects, to tidy up the scripts

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-:-O-esNGk8ztWq8oCLUuM:b-9pj458)* status: all files reviewed, 4 unresolved discussions (waiting on @g-pyxl)

___
*[`okd_qc_commands.py` line 11 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-esFpH64d1qlCia0wq:-O-esFpH64d1qlCia0wr:b-rlyry8) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L11)):*
> ```Python
> 
> Usage:
>     python3 qcgen.py -p {dnanexus_project_id} -f {illumina_runfolder_name}
> ```

could you update the script name?
___
*[`okd_qc_commands.py` line 78 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-evLer-wkH4illQP-n:-O-evLer-wkH4illQP-o:b-jlh1gs) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L78)):*
> ```Python
> 
>                 # Write the FastQC command for each pair of fastq files
>                 script_file.write(
> ```

You could use f strings here, which can make the code easier to follow
___
*[`okd_qc_commands.py` line 133 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-evm8lCYvE3FKS9Pvk:-O-evm8lCYvE3FKS9Pvl:bvnb7yy) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L133)):*
> ```Python
>     
>     # Read the DNAnexus auth token from file
>     auth_token = read_auth_token("/usr/local/src/mokaguys/.dnanexus_auth_token")
> ```

Suggestion to add this as a command line arg instead of the path to the secret
___
*[`README.md` line 73 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-f04H6CCwuPRbrkQCE:-O-f04H6CCwuPRbrkQCF:b1we1pt) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/README.md#L73)):*
> ```Markdown
> ### Usage:
> ```
> python3 qcgen.py -p {dnanexus_project_id} -f {illumina_runfolder_name}
> ```

Could you update the script name here

**Review by g-pyxl — COMMENTED** [review]
Added to repo.

> *[Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-:-O08aXSO-LZnSR13w_6c:bfw83oc)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @RachelDuffin)

___
*[`README.md` line 73 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-f04H6CCwuPRbrkQCE:-O-f4f7ACumiXtMWeLvk:b-896fix) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/README.md#L73)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Could you update the script name here
</blockquote></details>

Done.
___
*[`okd_qc_commands.py` line 11 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-esFpH64d1qlCia0wq:-O-f4_w02VmxeMGi-qn4:b-896fix) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L11)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

could you update the script name?
</blockquote></details>

Done.
___
*[`okd_qc_commands.py` line 78 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-evLer-wkH4illQP-n:-O08aIsaDHPaSu82feWD:blr13hx) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L78)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

You could use f strings here, which can make the code easier to follow
</blockquote></details>

Done, temporarily removing script until genomics server is live
___
*[`okd_qc_commands.py` line 133 at r1](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-O-evm8lCYvE3FKS9Pvk:-O08aSHk6j_8DOGOfpi3:blr13hx) ([raw file](https://github.com/moka-guys/adhoc_scripts/blob/de227051b6ad5b474b85cb3094e0c005b2e47373/okd_qc_commands.py#L133)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Suggestion to add this as a command line arg instead of the path to the secret
</blockquote></details>

Done, temporarily removing script until genomics server is live

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10)* status: 5 of 6 files reviewed, all discussions resolved

**Review by RachelDuffin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10#-:-O08uQfl8ggME4lw4I0a:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/adhoc_scripts/10)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @g-pyxl)

**Pull request merged**
